### ISSUE TITLE
Kernal64 emulator supports MagicDesk128

### ISSUE THREAD

**Issue by abbruzze** [RetroNynjah/Magic-Desk-128#1]
Hi,
just to let you know that my emulator Kernal64 (https://github.com/abbruzze/kernal64) supports MagicDesk128.
I test it with VolleyForTwo game and it seems to work fine.

Have you any other cart for testing ?

Thanks.

**Comment by RetroNynjah** [comment]
Hi,

Thanks a lot for adding support for the format to your emulator! It makes software development so much easier when it's possible to test an image without first burning to ROM.

The only other images that I know of that can be run on these cartridges are the multi-images that are created using Zzarko's Magic Cartridge Generator (https://bitbucket.org/zzarko/magic-cartridge-generator)
I think that he even has a sample bin file in his repository that should be possible to test with.

How do you attach this kind of cartridges in kernal64? Must the bin-files be converted to crt format somehow?

**Comment by abbruzze** [comment]
Ah, it's true, I testet Zzarko's images as well and worked fine.

To attach the bin (just the bin without any convertion) go to Setting -> ROMs and in the dialog on C128 Internal Function section:

1. uncheck none
2. select from drop down list MAGICDESK128 type
3. insert path to your bin file
4. click on Apply button

For now, I put the MagicDesk128 on internal function rom section only, even if I don't really understand if it is correct.
