### ISSUE TITLE
What happens when reading IO1?

### ISSUE THREAD

**Issue by mrdudz** [RetroNynjah/Magic-Desk-128#3]
If i read the schematic correctly, the register (bank) latch is loaded on any IO1 access - regardless of read or write. that means any read in the $de00-$deff range would potentially corrupt that register (simelar problem as AR5 has). Is that correct?

**Comment by RetroNynjah** [comment]
That is correct.
The same would be true for most Magic Desk designs for the C64 as far as I can see. I haven't seen any design that takes R/W into account.
I have added information about this to the README.
Thanks for catching it!
